name: Docker Image Spot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/fastapi-spot:1.17 .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/fastapi-spot:1.17

      
